apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Helm.fullname" . }}
  labels:
    {{- include "Helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "Helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name | lower }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
        
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}


      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      

