apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primenest-pvc
spec:
  storageClassName: PrimeNestStorageClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi