apiVersion: v1
kind: Secret
metadata:
  name: primenest-secret
type: Opaque
stringData:
  jwt-Key: zsrextdrcyftvugybnhumijpokyt12345678!@#$%^&*()_
  connectionString: "workstation id=PrimeDB1.mssql.somee.com;packet size=4096;user id=Redasaad123_SQLLogin_1;pwd=tobz3nhm3p;data source=PrimeDB1.mssql.somee.com;persist security info=False;initial catalog=PrimeDB1;TrustServerCertificate=True"